# Owner: Galina Larina
# Created: 2022-09-20

# This view contains order-level metrics for Post Order pod


view: daily_post_order_contact_rate_aggregates {
  sql_table_name: `flink-data-prod.reporting.daily_post_order_contact_rate_aggregates`;;
  view_label: "Daily Post Order Contact Rate Aggregates"

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~     Sets    ~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  set: dimensions {
    fields: [
      user_id,
      anonymous_id,
      order_id,
      order_uuid
    ]
  }

  set: device_information {
    fields: [
      app_version,
      device_type,
      platform
    ]
  }
  set: order_attributes {
    fields: [
      country_iso,
      delivery_timeliness,
      hub_code,
      order_state
    ]
  }

  set: flags {
    fields: [
      is_first_order,
      is_order_tracking_viewed,
      is_order_tracking_viewed_status_confirmation,
      is_order_tracking_viewed_status_packing,
      is_order_tracking_viewed_status_on_way,
      is_order_tracking_viewed_status_delivered,
      is_contact_cs,
      is_contact_cs_status_confirmation,
      is_contact_cs_status_packing,
      is_contact_cs_status_on_way,
      is_contact_cs_status_delivered
    ]
  }

  # set: date_timestamp {
  #   fields: [
  #     event_date,
  #     order_placed_timestamp,
  #     first_order_tracking_viewed_status_confirmation_timestamp,
  #     first_order_tracking_viewed_status_packing_timestamp,
  #     first_order_tracking_viewed_status_on_way_timestamp,
  #     first_order_tracking_viewed_status_delivered_timestamp,
  #     first_contact_cs_timestamp,
  #     first_contact_cs_status_confirmation_timestamp,
  #     first_contact_cs_status_packing_timestamp,
  #     first_contact_cs_status_on_way_timestamp,
  #     first_contact_cs_status_delivered_timestamp
  #   ]
  # }


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~     Dimensions    ~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  # ======= IDs ======= #

  dimension: user_id {
    group_label: "IDs"
    label: "User UUID"
    type: string
    hidden: yes
    description: "A unique ID for each user set upon account creation. This ID is passed under all behaviorual events when a user is logged in and is identical to the External ID under back-end models such as \"orders\"."
    sql: ${TABLE}.user_id ;;
  }

  dimension: anonymous_id {
    group_label: "IDs"
    label: "Anonymous ID"
    type: string
    hidden: yes
    description: "A unique ID for each user set by Segement."
    sql: ${TABLE}.anonymous_id ;;
  }

  dimension: order_id {
    group_label: "IDs"
    label: "Order ID"
    type: string
    hidden: yes
    description: "A unique identifier generated by back-end when an order is placed."
    sql: ${TABLE}.order_id ;;
  }

  dimension: order_uuid {
    group_label: "IDs"
    label: "Order UUID"
    primary_key: yes
    type: string
    hidden: yes
    description: "A unique identifier generated by back-end when an order is placed. It consists of a 'country_iso' prefix and the actual 'order_id'.
    This field appears within product data under \"event_order_placed\" and \"daily_user_aggregates\" models as well as back-end based data models such as \"orders\" and \"order_lineitems\"."
    sql: ${TABLE}.order_uuid ;;
  }

  # ======= Device information ======= #

  dimension: app_version {
    label: "App Version"
    group_label: "Device information"
    type: string
    hidden: no
    description: "Version of the app released, available for apps only."
    sql: ${TABLE}.app_version ;;
  }

  dimension: device_type {
    label: "Device Type"
    group_label: "Device information"
    type: string
    hidden: yes
    description: "Type of the device used, e.i. ios, android, windows etc."
    sql: ${TABLE}.device_type ;;
  }

  dimension: platform {
    label: "Platform"
    group_label: "Device information"
    type: string
    hidden: no
    description: "Platform which user used, can be 'web' or 'app'."
    sql: ${TABLE}.platform ;;
  }

# ======= Order attributes ======= #

  dimension: country_iso {
    label: "Country ISO"
    group_label: "Order attributes"
    type: string
    hidden: no
    description: "Country ISO based on 'hub_code'."
    sql: ${TABLE}.country_iso ;;
  }

  dimension: delivery_timeliness {
    label: "Delivery timeliness"
    group_label: "Order attributes"
    type: string
    description: "Whether the order was delivered early, on time or was late"
    sql: ${TABLE}.delivery_timeliness ;;
  }

  dimension: hub_code {
    label: "Hub Code"
    group_label: "Order attributes"
    type: string
    hidden: yes
    description: "Code of a hub identical to back-end source tables."
    sql: ${TABLE}.hub_code ;;
  }

  dimension: order_state {
    label: "Order State"
    group_label: "Order attributes"
    type: string
    description: "Whether the order was completed, cancelled, confirmed, etc."
    sql: ${TABLE}.order_state ;;
  }

# ======= Flags ======= #

  dimension: is_first_order {
    group_label: "Flags"
    label: "Is First Order"
    type: yesno
    description: "Is an order a first one"
    sql: ${TABLE}.is_first_order ;;
  }

  dimension: next_7_days_order_uuid {
    group_label: "Flags"
    label: "Next Order UUID"
    type: string
    description: "The next order UUID during 7 day window "
    sql: ${TABLE}.next_7_days_order_uuid ;;
  }

  dimension: has_next_order {
    group_label: "Flags"
    label: "Is the customer placed another order in next 7 days "
    type: yesno
    description: "Whether the customer has placed an order after the current order during 7 days "
    sql: ${TABLE}.next_7_days_order_uuid is not null;;
  }

  dimension: is_order_tracking_viewed {
    group_label: "Flags"
    label: "Is Order Tracking Viewed"
    type: yesno
    description: "Whether status of the order tracked by a customer"
    sql: ${TABLE}.is_order_tracking_viewed ;;
  }

  dimension: is_order_tracking_viewed_status_confirmation {
    group_label: "Flags"
    label: "Is Order Tracking Viewed Confirmation"
    type: yesno
    description: "Whether status of the order tracked by a customer while the order_status = 'confirmation'"
    sql: ${TABLE}.is_order_tracking_viewed_status_confirmation ;;
  }

  dimension: is_order_tracking_viewed_status_packing {
    group_label: "Flags"
    label: "Is Order Tracking Viewed Packing"
    type: yesno
    description: "Whether status of the order tracked by a customer while the order_status = 'packing'"
    sql: ${TABLE}.is_order_tracking_viewed_status_packing ;;
  }

  dimension: is_order_tracking_viewed_status_on_way {
    group_label: "Flags"
    label: "Is Order Tracking Viewed On Way"
    type: yesno
    description: "Whether status of the order tracked by a customer while the order_status = 'on way'"
    sql: ${TABLE}.is_order_tracking_viewed_status_on_way ;;
  }

  dimension: is_order_tracking_viewed_status_delivered {
    group_label: "Flags"
    label: "Is Order Tracking Viewed Delivered"
    type: yesno
    description: "Whether status of the order tracked by a customer while the order_status = 'delivered'"
    sql: ${TABLE}.is_order_tracking_viewed_status_delivered ;;
  }

  dimension: is_contact_cs {
    group_label: "Flags"
    label: "Is Contact Customer Service Selected"
    type: yesno
    description: "Whether a customer triggered contact_customer_service_selected after the order was placed"
    sql: ${TABLE}.is_contact_cs ;;
  }

  dimension: is_contact_cs_status_confirmation {
    group_label: "Flags"
    label: "Is Contact Customer Service Selected Confirmation"
    type: yesno
    description: "Whether a customer triggered contact_customer_service_selected while the order_status = 'confirmation'"
    sql: ${TABLE}.is_contact_cs_status_confirmation ;;
  }

  dimension: is_contact_cs_status_packing {
    group_label: "Flags"
    label: "Is Contact Customer Service Selected Packing"
    type: yesno
    description: "Whether a customer triggered contact_customer_service_selected while the order_status = 'packing'"
    sql: ${TABLE}.is_contact_cs_status_packing ;;
  }

  dimension: is_contact_cs_status_on_way {
    group_label: "Flags"
    label: "Is Contact Customer Service Selected On Way"
    type: yesno
    description: "Whether a customer triggered contact_customer_service_selected while the order_status = 'on way'"
    sql: ${TABLE}.is_contact_cs_status_on_way ;;
  }

  dimension: is_contact_cs_status_delivered {
    group_label: "Flags"
    label: "Is Contact Customer Service Selected Delivered"
    type: yesno
    description: "Whether a customer triggered contact_customer_service_selected while the order_status = 'delivered'"
    sql: ${TABLE}.is_contact_cs_status_delivered ;;
  }


  # =======  Date Timestamp ======= #

  dimension_group: event_date {
    group_label: "Date Timestamp"
    label: "Event Date"
    type: time
    timeframes: [
      date,
      day_of_week,
      week,
      month,
      month_name,
      quarter,
      year
    ]
    datatype: date
    sql: ${TABLE}.event_date ;;
  }

  dimension_group: order_placed_timestamp {
    group_label: "Date Timestamp"
    label: "Timestamp Order Placed"
    type: time
    description: "Timestamp when an order was placed, as available in the back-end model 'orders'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.order_placed_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }


  dimension_group: first_order_tracking_viewed_status_confirmation_timestamp {
    group_label: "Date Timestamp"
    label: "First Order Tracking Viewed Confirmation Timestamp"
    type: time
    description: "First timetsamp when a customer triggered order_tracking_viewed while the order_status = 'confirmation'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_order_tracking_viewed_status_confirmation_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_order_tracking_viewed_status_packing_timestamp {
    group_label: "Date Timestamp"
    label: "First Order Tracking Viewed Packing Timestamp"
    type: time
    description: "First timetsamp when a customer triggered order_tracking_viewed while the order_status = 'packing'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_order_tracking_viewed_status_packing_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_order_tracking_viewed_status_on_way_timestamp {
    group_label: "Date Timestamp"
    label: "First Order Tracking Viewed On Way Timestamp"
    type: time
    description: "First timetsamp when a customer triggered order_tracking_viewed while the order_status = 'on way'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_order_tracking_viewed_status_on_way_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_order_tracking_viewed_status_delivered_timestamp {
    group_label: "Date Timestamp"
    label: "First Order Tracking Viewed Delivered Timestamp"
    type: time
    description: "First timetsamp when a customer triggered order_tracking_viewed while the order_status = 'delivered'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_order_tracking_viewed_status_delivered_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_contact_cs_timestamp {
    group_label: "Date Timestamp"
    label: "First Contact Customer Support Timestamp"
    type: time
    description: "First timetsamp when a customer triggered contact_customer_support for the placed order"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_contact_cs_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_contact_cs_status_confirmation_timestamp {
    group_label: "Date Timestamp"
    label: "First Contact Customer Support Confirmation Timestamp"
    type: time
    description: "First timetsamp when a customer triggered contact_customer_support while the order_status = 'confirmation'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_contact_cs_status_confirmation_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_contact_cs_status_packing_timestamp {
    group_label: "Date Timestamp"
    label: "First Contact Customer Support Packing Timestamp"
    type: time
    description: "First timetsamp when a customer triggered contact_customer_support while the order_status = 'packing'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_contact_cs_status_packing_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_contact_cs_status_on_way_timestamp {
    group_label: "Date Timestamp"
    label: "First Contact Customer Support On Way Timestamp"
    type: time
    description: "First timetsamp when a customer triggered contact_customer_support while the order_status = 'on way'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_contact_cs_status_on_way_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }

  dimension_group: first_contact_cs_status_delivered_timestamp {
    group_label: "Date Timestamp"
    label: "First Contact Customer Support Delivered Timestamp"
    type: time
    description: "First timetsamp when a customer triggered contact_customer_support while the order_status = 'delivered'"
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.first_contact_cs_status_delivered_timestamp ;;
    datatype: timestamp
    convert_tz: no
  }


  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~     Measures    ~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  measure: number_of_orders {
    type: count_distinct
    sql:  ${order_uuid};;
  }

  measure: number_of_order_ccsi{
    type: count_distinct
    label: "Number of Orders with CCS Intent"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_contact_cs: "yes"]
  }

  measure: number_of_order_ccsi_confirmed{
    type: count_distinct
    label: "Number of Orders with CCS Intent Status Confirmed"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_contact_cs_status_confirmation: "yes"]
  }

  measure: number_of_order_ccsi_packing{
    type: count_distinct
    label: "Number of Orders with CCS Intent Status Packing"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_contact_cs_status_packing: "yes"]
  }

  measure: number_of_order_ccsi_on_way{
    type: count_distinct
    label: "Number of Orders with CCS Intent Status On Way"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_contact_cs_status_on_way: "yes"]
  }

  measure: number_of_order_ccsi_delivered{
    type: count_distinct
    label: "Number of Orders with CCS Intent Status Delivered"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_contact_cs_status_delivered: "yes"]
  }

  measure: number_of_order_otv_confirmed{
    type: count_distinct
    label: "Number of Orders with Tracked Status Confirmed"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_order_tracking_viewed_status_confirmation: "yes"]
  }

  measure: number_of_order_otv_packing{
    type: count_distinct
    label: "Number of Orders with Tracked Status Packing"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_order_tracking_viewed_status_packing: "yes"]
  }

  measure: number_of_order_otv_on_way{
    type: count_distinct
    label: "Number of Orders with Tracked Status On Way"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_order_tracking_viewed_status_on_way: "yes"]
  }

  measure: number_of_order_otv_delivered{
    type: count_distinct
    label: "Number of Orders with Tracked Status Delivered"
    hidden:  no
    sql: ${order_uuid} ;;
    filters: [is_order_tracking_viewed_status_delivered: "yes"]
  }

######## * Percentages * ########

  measure: pct_orders_ccs_intent {
    group_label: "* Percentages *"
    label: "% CCS Intent"
    description: "# orders with CCS intent divided by the total # orders."
    type: number
    sql: (1.0 * ${number_of_order_ccsi}) / NULLIF(${number_of_orders}, 0) ;;
    value_format_name: percent_1
  }

  measure: pct_orders_ccs_intent_step1 {
    group_label: "* Percentages *"
    label: "% CCS Intent On Order Confirmation"
    description: "# orders with CCS intent on the order confirmation step divided by the total # orders."
    type: number
    sql: (1.0 * ${number_of_order_ccsi_confirmed}) / NULLIF(${number_of_orders}, 0) ;;
    value_format_name: percent_1
  }

  measure: pct_orders_ccs_intent_step2 {
    group_label: "* Percentages *"
    label: "% CCS Intent On Order Packing"
    description: "The number of orders with CCS intent on the order confirmation step divided by the total number of orders."
    type: number
    sql: (1.0 * ${number_of_order_ccsi_packing}) / NULLIF(${number_of_orders}, 0) ;;
    value_format_name: percent_1
  }

  measure: pct_orders_ccs_intent_step3 {
    group_label: "* Percentages *"
    label: "% CCS Intent On Order On Way"
    description: "The number of orders with CCS intent on the order confirmation step divided by the total number of orders."
    type: number
    sql: (1.0 * ${number_of_order_ccsi_on_way}) / NULLIF(${number_of_orders}, 0) ;;
    value_format_name: percent_1
  }

  measure: pct_orders_ccs_intent_step4 {
    group_label: "* Percentages *"
    label: "% CCS Intent On Order Delivered"
    description: "The number of orders with CCS intent on the order confirmation step divided by the total number of orders."
    type: number
    sql: (1.0 * ${number_of_order_ccsi_delivered}) / NULLIF(${number_of_orders}, 0) ;;
    value_format_name: percent_1
  }

  ######## * Times & Durations * ########

  dimension: time_ccs_intent_since_order_duration {
    label: "Time CCS Intent Since Order (minutes)"
    group_label: "* Times & Durations *"
    description: "# minutes since the order was placed."
    type: duration_minute
    sql_start: ${order_placed_timestamp_raw} ;;
    sql_end: ${first_contact_cs_timestamp_raw};;
  }

  dimension: time_since_order_tiers {
    group_label: "* Times & Durations *"
    label: "Time Since Order Tiers (minutes)"
    description: "Tiers of Time Since Order [0, >60)"
    type: tier
    tiers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 25, 30, 45, 60]
    style: interval
    sql: ${time_ccs_intent_since_order_duration} ;;
  }
################## Parameter and Dynamic Dates


  parameter: date_granularity {
    group_label: "* Dates and Timestamps *"
    label: "Date Granularity"
    type: unquoted
    allowed_value: { value: "Day" }
    allowed_value: { value: "Week" }
    allowed_value: { value: "Month" }
    default_value: "Day"
  }
######## DYNAMIC DIMENSIONS

  dimension: date {
    group_label: "* Dates & Timestamps *"
    label: "Contact Date (Dynamic)"
    label_from_parameter: date_granularity
    sql:
    {% if date_granularity._parameter_value == 'Day' %}
      ${event_date_date}
    {% elsif date_granularity._parameter_value == 'Week' %}
      ${event_date_week}
    {% elsif date_granularity._parameter_value == 'Month' %}
      ${event_date_month}
    {% endif %};;
  }

  dimension: date_granularity_pass_through {
    group_label: "* Parameters *"
    description: "To use the parameter value in a table calculation (e.g WoW, % Growth) we need to materialize it into a dimension "
    type: string
    hidden: no # yes
    sql:
            {% if date_granularity._parameter_value == 'Day' %}
              "Day"
            {% elsif date_granularity._parameter_value == 'Week' %}
              "Week"
            {% elsif date_granularity._parameter_value == 'Month' %}
              "Month"
            {% endif %};;
  }


}
