view: event_outbound_progressed {
  sql_table_name: `flink-data-prod.curated.event_outbound_progressed`
    ;;

  view_label: "1 Event: Outbound Progressed"

  # This is the curated table for Outbound Progressed event coming from Hub One

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Sets          ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  set: to_include_dimensions {
    fields: [
      action,
      dropping_list_id,
      product_sku,
      quantity_damaged,
      quantity_expired,
      quantity_perished,
      quantity_received
    ]
  }

  set: to_include_measures {
    fields: [
      number_of_dropping_lists,
      number_of_distinct_products_outbounded,
      number_of_distinct_products_added_to_outbound,
      sum_quantity_damaged,
      sum_quantity_expired,
      sum_quantity_perished,
      sum_quantity_received
    ]
  }

  set: to_include_set {
    fields: [to_include_dimensions*, to_include_measures*]
  }
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Parameters     ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Dimensions     ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # =========  IDs   =========

  dimension: event_uuid {
    type: string
    group_label: "IDs"
    label: "Event UUID"
    description: "Unique identifier of an event"
    primary_key: yes
    hidden: yes
    sql: ${TABLE}.event_uuid ;;
  }

  dimension: anonymous_id {
    type: string
    group_label: "IDs"
    label: "Anonymous ID"
    description: "User ID set by Segment"
    hidden: yes
    sql: ${TABLE}.anonymous_id ;;
  }

# =========  Location Attributes   =========

  dimension: country_iso {
    type: string
    group_label: "Location Dimensions"
    label: "Country ISO"
    description: "Country ISO based on 'hub_code'."
    sql: ${TABLE}.country_iso ;;
  }

  dimension: hub_code {
    type: string
    group_label: "Location Dimensions"
    label: "Hub Code"
    description: "Code of a hub identical to back-end source tables."
    sql: ${TABLE}.hub_code ;;
  }

  dimension: locale {
    group_label: "Location Dimensions"
    label: "Locale"
    description: "Language code | Coutnry, region code"
    type: string
    sql: ${TABLE}.locale ;;
  }

  # =========  Employee Attributes   =========

  dimension: quinyx_badge_number {
    type: string
    group_label: "Employee Attributes"
    label: "Quinyx Badge Number"
    sql: ${TABLE}.quinyx_badge_number ;;
  }

  dimension: user_id {
    type: string
    group_label: "Employee Attributes"
    label: "Auth0 id" #Not yet but it should be
    hidden: yes
    sql: ${TABLE}.user_id ;;
  }

  # =========  Dates and Timestamps   =========

  dimension_group: received {
    type: time
    hidden: yes
    sql: ${TABLE}.received_at ;;
  }

  dimension_group: event {
    type: time
    hidden: yes
    convert_tz: no
    datatype: date
    sql: ${TABLE}.event_date ;;
  }

  dimension_group: event_timestamp {
    group_label: "Date / Timestamp"
    label: "Event"
    description: "Timestamp of when an event happened"
    type: time
    timeframes: [
      time,
      date,
      week,
      hour_of_day,
      quarter
    ]
    sql: ${TABLE}.event_timestamp ;;
  }

  dimension_group: original_timestamp {
    hidden: yes
    type: time
    description: "Timestamp on the client device when call was invoked."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.original_timestamp ;;
  }

  # =========  Generic Dimensions   =========

  dimension: event_name {
    group_label: "Generic Dimensions"
    label: "Event Name"
    description: "Name of the event triggered"
    type: string
    sql: ${TABLE}.event_name ;;
  }

  dimension: event_text {
    group_label: "Generic Dimensions"
    label: "Event Text"
    description: "event_name in camel case"
    type: string
    hidden: yes
    sql: ${TABLE}.event_text ;;
  }

  dimension: screen_name {
    group_label: "Generic Dimensions"
    label: "Screen Name"
    description: "Screen name where the event was triggered"
    type: string
    sql: ${TABLE}.screen_name ;;
  }

# =========  Event Dimensions   =========

  dimension: action {
    group_label: "Outbound Progressed Dimensions"
    description: "The action performed."
    type: string
    sql: ${TABLE}.action ;;
  }

  dimension: dropping_list_id {
    group_label: "Outbound Progressed Dimensions"
    type: string
    description: "Unique identifier generated by back-end when the inbound process is started (legacy inventory_movement_id)."
    sql: ${TABLE}.dropping_list_id ;;
  }

  dimension: product_sku {
    group_label: "Outbound Progressed Dimensions"
    description: "The sku of the product, as available in the backend."
    type: string
    sql: ${TABLE}.product_sku ;;
  }

  dimension: quantity_damaged {
    group_label: "Outbound Progressed Dimensions"
    type: number
    description: "Number of units reported as damaged by the employee while performing the task. Value coming from Hub One."
    sql: ${TABLE}.quantity_damaged ;;
  }

  dimension: quantity_expired {
    group_label: "Outbound Progressed Dimensions"
    type: number
    description: "Number of units reported as expired by the employee while performing the task. Value coming from Hub One."
    sql: ${TABLE}.quantity_expired ;;
  }

  dimension: quantity_perished {
    group_label: "Outbound Progressed Dimensions"
    type: number
    description: "Number of units reported as perished by the employee while performing the task. Value coming from Hub One."
    sql: ${TABLE}.quantity_perished ;;
  }

  dimension: quantity_received {
    group_label: "Outbound Progressed Dimensions"
    type: number
    description: "Number of units reported as damaged by the employee while performing the task. Value coming from Hub One."
    sql: ${TABLE}.quantity_received ;;
  }

  # =========  Other Dimensions   =========

  dimension: context_ip {
    type: string
    hidden: yes
    sql: ${TABLE}.context_ip ;;
  }

  dimension: page_path {
    type: string
    hidden: yes
    sql: ${TABLE}.page_path ;;
  }

  dimension: page_title {
    type: string
    hidden: yes
    sql: ${TABLE}.page_title ;;
  }

  dimension: page_url {
    type: string
    hidden: yes
    sql: ${TABLE}.page_url ;;
  }

  dimension: user_agent {
    type: string
    hidden: yes
    sql: ${TABLE}.user_agent ;;
  }

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~      Measures     ~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  # =========  Total Metrics   =========

  measure: number_of_events {
    group_label: "Outbound Total Metrics"
    label: "# Events"
    description: "Number of events triggered"
    type: count_distinct
    sql: ${TABLE}.event_uuid ;;
  }

  measure: number_of_dropping_lists {
    group_label: "Outbound Total Metrics"
    label: "# Dropping Lists"
    description: "Number of Dropping Lists with at least one product added to outbound."
    type: count_distinct
    sql: ${dropping_list_id} ;;
  }

  measure: number_of_distinct_products_outbounded {
    group_label: "Outbound Total Metrics"
    label: "Number of distinct products outbounded"
    description: "Count distinct product_sku when action = product_outbounded"
    type: count_distinct
    filters: [action: "product_outbounded"]
    sql: ${product_sku} ;;
  }

  measure: number_of_distinct_products_added_to_outbound {
    group_label: "Outbound Total Metrics"
    label: "Number of distinct products added to outbound"
    description: "Count distinct product_sku when action = product_added_to_outbound"
    type: count_distinct
    filters: [action: "product_added_to_outbound"]
    sql: ${product_sku} ;;
  }

  measure: sum_quantity_damaged {
    group_label: "Outbound Total Metrics"
    type: sum
    description: "Number of units reported as damaged by the employee while performing the task. Value coming from Hub One."
    sql: ${quantity_damaged} ;;
  }

  measure: sum_quantity_expired {
    group_label: "Outbound Total Metrics"
    type: sum
    description: "Number of units reported as expired by the employee while performing the task. Value coming from Hub One."
    sql: ${quantity_expired} ;;
  }

  measure: sum_quantity_perished {
    group_label: "Outbound Total Metrics"
    type: sum
    description: "Number of units reported as perished by the employee while performing the task. Value coming from Hub One."
    sql: ${quantity_perished} ;;
  }

  measure: sum_quantity_received {
    group_label: "Outbound Total Metrics"
    type: sum
    description: "Number of units reported as damaged by the employee while performing the task. Value coming from Hub One."
    sql: ${quantity_received} ;;
  }

  # =========  Rate Metrics   =========

}
