# Owner: Product Analytics, Flavia Alvarez
# Created: 2022-09-12

view: inventory_movement_id_times {
  derived_table: {
    explore_source: daily_stock_management_events {
      column: inventory_movement_id {}
      column: cart_created_time {}
      column: dropping_list_created_time {}
      column: dropping_list_finished_time {}
      column: cart_to_drop_list_seconds {}
      column: drop_list_created_to_finished_seconds {}
      column: cart_to_finished_seconds {}
      column: event_timestamp_date {}
      bind_all_filters: yes
      filters: {
        field: daily_stock_management_events.event_name
        value: "\"inventory_state_updated\""
      }
    }
  }

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~     Dimensions     ~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  dimension: inventory_movement_id {
    primary_key: yes
    label: "Daily Stock Management Events Inventory Movement Id"
    description: "A unique identifier generated by back-end when an inventory movement is started (inbound, outbound or correction)."
  }
  dimension: cart_created_time {
    description: "Timestamp for when the cart has been created."
    type: number
  }
  dimension: dropping_list_created_time {
    description: "Timestamp for when the dropping list has been created."
    type: number
  }
  dimension: dropping_list_finished_time {
    description: "Timestamp for when the dropping list has been finished."
    type: number
  }
  dimension: cart_to_drop_list_seconds {
    description: "Difference in seconds between time_to_cart_created and time_to_dropping_list timestamps"
    type: number
  }
  dimension: drop_list_created_to_finished_seconds {
    description: "Difference in seconds between time_to_dropping_list_created and time_to_dropping_list_finished timestamps"
    type: number
  }
  dimension: cart_to_finished_seconds {
    description: "Difference in seconds between time_to_cart_created and time_to_dropping_list_finished timestamps"
    type: number
  }

  dimension: event_timestamp_date {
    hidden: yes
    label: "Event Date"
    description: "Timestamp of when an event happened"
    type: date
  }

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~     Measures     ~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # Note that for this measures to be accurate we need to use sum_distinct with sql_distinct_key = order_id
  # This is because this view is being joined to daily_events and if we use a normal sum it will be suming
  # duplicate values

  measure: sum_of_cart_to_drop_list_seconds {
    label: "Cart To Drop List seconds"
    description: "Sum of cart_to_drop_list time in seconds."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${inventory_movement_id} ;;
    sql: ${cart_to_drop_list_seconds} ;;
  }

  measure: sum_of_drop_list_created_to_finished_seconds {
    label: "Drop List Created to Finished seconds"
    description: "Sum of drop_list_created_to_finished time in seconds."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${inventory_movement_id} ;;
    sql: ${drop_list_created_to_finished_seconds} ;;
  }

  measure: sum_of_cart_to_finished_seconds {
    label: "Cart to Finished seconds"
    description: "Sum of cart_to_finished time in seconds."
    type: sum_distinct
    value_format: "0.#"
    sql_distinct_key: ${inventory_movement_id} ;;
    sql: ${cart_to_finished_seconds} ;;
  }
}
