# Owner: Lauti Ruiz

# Description: This view shows products (items) data according to our ERP Systems.
#              Until 2023-01-20 this data comes from Lexbizz ERP,
#              after that date, comes from Oracle.

# Lexbizz : curated.lexbizz_item ->> Until 2023-01-20
# Oracle : curated.oracle_item_daily ->> From 2023-01-20


view: erp_item {
  sql_table_name: `flink-data-prod.curated.erp_item`
    ;;

#############################################
############## Date Dimensions ##############
#############################################

  dimension_group: ingestion {
    type: time
    timeframes: [
      date
    ]
    datatype: date
    description: "Date on which data was extracted from an external tool/api and stored into a BigQuery table."
    sql: ${TABLE}.ingestion_date ;;
    group_label: "Dates & Timestamps"
  }

  dimension_group: introduction_timestamp {
    type: time
    description: "The date, when a given product was listed initially."
    timeframes: [
      time,
      date
    ]
    sql: ${TABLE}.introduction_timestamp ;;
    group_label: "Dates & Timestamps"
  }

  dimension_group: item_status_update {
    type: time
    description: " The date, when the item status changed the last time."
    timeframes: [
      date
    ]
    datatype: date
    sql: ${TABLE}.item_status_update ;;
    group_label: "Dates & Timestamps"
  }

  dimension_group: last_modified_timestamp {
    type: time
    description: "Timestamp generated by the backend representing
                  when some record/row in the raw data was updated the last time."
    timeframes: [
      time,
      date
    ]
    sql: ${TABLE}.last_modified_timestamp ;;
    group_label: "Dates & Timestamps"
    hidden: yes
  }

  dimension_group: termination_timestamp {
    type: time
    description: "The timestamp, when a given product was delisted."
    timeframes: [
      time,
      date
    ]
    sql: ${TABLE}.termination_timestamp ;;
    group_label: "Dates & Timestamps"
  }

#############################################
############## IDs Dimensions ###############
#############################################

  dimension: table_uuid {
    type: string
    sql: ${TABLE}.table_uuid ;;
    hidden: yes
    primary_key: yes
    description: "Generic identifier of a table that represent 1 unique row."
  }


#############################################
################ Flags Dimensions ###########
#############################################

  dimension: is_orderable {
    label: "Is Item Orderable"
    type: yesno
    sql: ${TABLE}.is_orderable ;;
    description: "This boolean field is an indicator,
                  whether an SKU is orderable by the Supply Chain department."
    group_label: "Product Attribute"
  }

  dimension: is_perishable {
    label: "Is Item Perishable"
    type: yesno
    sql: ${TABLE}.is_perishable ;;
    description: "This boolean field is an indicator, whether an SKU can perish."
    group_label: "Product Attribute"
  }

  dimension: is_sellable {
    label: "Is Item Sellable"
    type: yesno
    sql: ${TABLE}.is_sellable ;;
    description: "This boolean field is an indicator, whether an SKU is sellable."
    group_label: "Product Attribute"
  }

#############################################
############## General Dimensions ###########
#############################################

  dimension: base_uom {
    label: "Base UOM"
    type: string
    sql: ${TABLE}.base_uom ;;
    description: "The base unit of measure of a product"
    group_label: "Product Attribute"
  }

  dimension: country_iso {
    label: "Country ISO"
    type: string
    sql: ${TABLE}.country_iso ;;
    description: "2-letter country code."
  }

  dimension: description {
    label: "Item Description"
    type: string
    sql: ${TABLE}.description ;;
    description: "The description of a product in CommerceTools"
    group_label: "Product Attribute"
  }

  dimension: ean {
    label: "EAN"
    type: string
    sql: ${TABLE}.ean ;;
    description: "The european article number (EAN) of a product"
    group_label: "IDs"
  }

  dimension: ean_hu {
    label: "EAN Handling Unit"
    type: string
    sql: ${TABLE}.ean_hu ;;
    description: "The european article number of a handling unit of a product"
    group_label: "IDs"
  }

  dimension: group_company {
    label: "Group Company"
    type: string
    sql: ${TABLE}.group_company ;;
    description: "The producing company of a product."
    group_label: "Product Attribute"
  }

  dimension: handling_unit_height {
    label: "Handling Unit Height"
    type: number
    sql: ${TABLE}.handling_unit_height ;;
    description: "The height of a handling unit"
    group_label: "Product Attribute (Measures)"
  }

  dimension: handling_unit_length {
    label: "Handling Unit Length"
    type: number
    sql: ${TABLE}.handling_unit_length ;;
    description: "The length of a handling unit"
    group_label: "Product Attribute (Measures)"
  }

  dimension: handling_unit_width {
    label: "Handling Unit Width"
    type: number
    sql: ${TABLE}.handling_unit_width ;;
    description: "The width of a handling unit"
    group_label: "Product Attribute (Measures)"
  }

  dimension: hub_type {
    label: "Hub Type"
    type: string
    sql: ${TABLE}.hub_type ;;
    description: "The hub type indicates, to which kind of hubs a given product is usually assigned to.
                  Hereby, an assignment to an M-hub indicates,
                  that the product is usually offered in all M hubs or bigger (L hubs)"
    group_label: "Product Attribute"
  }

  dimension: item_category {
    label: "Item Category"
    type: string
    sql: ${TABLE}.item_category ;;
    description: "The product parent category as defined in the ERP tool"
    group_label: "Product Attribute"
  }

  dimension: item_class {
    label: "Item Class"
    type: string
    sql: ${TABLE}.item_class ;;
    description: "The product class as defined in the ERP tool"
    group_label: "Product Attribute"
  }

  dimension: item_height {
    label: "Item Height"
    type: number
    sql: ${TABLE}.item_height ;;
    description: "The height of a product"
    group_label: "Product Attribute (Measures)"
  }

  dimension: item_length {
    label: "Item Length"
    type: number
    sql: ${TABLE}.item_length ;;
    description: "The length of a product"
    group_label: "Product Attribute (Measures)"
  }

  dimension: item_name {
    label: "Item Name"
    type: string
    sql: ${TABLE}.item_name ;;
    description: "The name of a product as defined in the ERP tool"
  }

  dimension: item_replenishment_substitute_group {
    label: "Item Replenishment Substitute Group"
    type: string
    sql: ${TABLE}.item_replenishment_substitute_group ;;
    description: "The replenishment substitute group defined by the Supply Chain team
                  to tag substitute products for replenishment."
  }

  dimension: item_safety_stock {
    label: "Item Safety Stock"
    type: number
    sql: ${TABLE}.item_safety_stock ;;
    description: "Minimun stock to have of a product to be safe"
    group_label: "Product Attribute"
  }

  dimension: item_status {
    label: "Item Status"
    type: string
    sql: ${TABLE}.item_status ;;
    description: "The activity/listing status of a product according to our ERP system"
  }

  dimension: item_substitute_group {
    label: "Item Substitute Group"
    type: string
    sql: ${TABLE}.item_substitute_group ;;
    description: "The substitute group according to the ERP defining substitute products."
  }

  dimension: item_type {
    label: "Item Type"
    type: string
    sql: ${TABLE}.item_type ;;
    description: "The type of a product as defined in the ERP tool"
    group_label: "Product Attribute"
  }

  dimension: item_volumne {
    label: "Item Volumne"
    type: number
    sql: ${TABLE}.item_volumne ;;
    description: "The volumne of a product"
    group_label: "Product Attribute (Measures)"
  }

  dimension: item_weight {
    label: "Item Weight"
    type: number
    sql: ${TABLE}.item_weight ;;
    description: "The weight of a product"
    group_label: "Product Attribute (Measures)"
  }

  dimension: item_width {
    label: "Item Width"
    type: number
    sql: ${TABLE}.item_width ;;
    description: "The width of a product"
    group_label: "Product Attribute (Measures)"
  }

  dimension: max_shelf_life_days {
    label: "Max Shelf Life Days"
    type: number
    sql: ${TABLE}.max_shelf_life_days ;;
    description: "Products's max amount of days on shelf."
    group_label: "Product Attribute"
  }

  dimension: min_days_to_best_before_date {
    label: "Min Days to best before date (BBD)"
    type: number
    sql: ${TABLE}.min_days_to_best_before_date ;;
    description: "The minimum duration required between the sale of the product and the BBD (in days)."
    group_label: "Product Attribute"
  }

#Are we going to have this data?
  dimension: msrp {
    label: "MSRP"
    type: number
    sql: ${TABLE}.msrp ;;
    hidden: yes
  }

#Are we going to have this data?
  dimension: noos_item {
    label: "NOOS Item"
    type: yesno
    sql: ${TABLE}.noos_item ;;
    hidden: yes
  }

#Are we going to have this data?
  dimension: noos_leading_product {
    label: "NOOS Leading Product"
    type: yesno
    sql: ${TABLE}.noos_leading_product ;;
    hidden: yes
  }

  dimension: purchase_unit {
    label: "Purchase Unit"
    type: string
    sql: ${TABLE}.purchase_unit ;;
    description: "The ERP defined puchase unit code of a product.
                  It defines, which aggregation was bought (examples: STÜCK, PK14, PK06)"
    group_label: "Product Attribute (Measures)"
  }

  dimension: purchase_uom {
    label: "Purchase UOM"
    type: string
    sql: ${TABLE}.purchase_uom ;;
    description: "The base unit of measure of a product purchase"
    group_label: "Product Attribute (Measures)"
  }

  dimension: sales_uom {
    label: "Sales UOM"
    type: string
    sql: ${TABLE}.sales_uom ;;
    description: "The base unit of measure of a product sale"
    group_label: "Product Attribute (Measures)"
  }

  dimension: seasonality {
    label: "Seasonality"
    type: string
    sql: ${TABLE}.seasonality ;;
    description: "Season where the product is available"
    group_label: "Product Attribute"
  }

  dimension: shelf_type {
    label: "Shelf Type"
    type: string
    sql: ${TABLE}.shelf_type ;;
    description: "Type of shelf where the product is stored"
    group_label: "Product Attribute"
  }

  dimension: sku {
    label: "SKU"
    type: string
    sql: ${TABLE}.sku ;;
    description: "SKU of the product, as available in the backend."
  }

  dimension: tax_category {
    label: "Tax Category"
    type: string
    sql: ${TABLE}.tax_category ;;
    description: "The specific tax category of a product"
    group_label: "Product Attribute"
  }

  dimension: temperature_zone {
    label: "Temperature Zone"
    type: string
    sql: ${TABLE}.temperature_zone ;;
    description: "Temperature a product needs to have while being delivered and stored in order to be consumable"
    group_label: "Product Attribute"
  }

  dimension: valuation_method {
    label: "Valuation Method"
    type: string
    sql: ${TABLE}.valuation_method ;;
    description: "The method used to valuate the product"
    group_label: "Product Attribute"
  }


#############################################
############## Generated Dimensions #########
#############################################

  dimension: similar_rsg {
    label: "Similar RSG"
    type: string
    sql: lower(left(${item_replenishment_substitute_group}, 10)) ;;
    group_label: "Special Uses Cases Data"
  }

  dimension: ean_length {
    label: "EAN Length"
    type: string
    sql: length(${ean}) ;;
    description: "The length of the EAN (count of digits)"
    group_label: "Special Uses Cases Data"
  }

  dimension: ean_matching_digits {
    label: "EAN Matching Digits"
    type: yesno
    sql: (${ean_length} = 8 or ${ean_length} = 13) ;;
    description: "Boolean that indicates that the EAN is correct, if it follows the 8 and 13 digits long"
    group_label: "Special Uses Cases Data"
  }

  dimension: is_leading_sku {
    label: "Is Leading SKU"
    type: yesno
    sql: left(${sku},1) = '9' ;;
    description: "Boolean that indicates if the product is a Parent SKU"
    group_label: "Special Uses Cases Data"
  }

  dimension: erp_ct_sync_check {
    type: yesno

    sql:
      lower(${base_uom})             = lower(${products.unit_of_measure})
      and replace(lower(${item_category}),' ', '')  = concat(lower(${products.erp_category}), lower(${products.erp_subcategory}))
      and ${item_name} = ${products.product_name}
      and ((${item_status} = 'Active' and ${products.is_published} is true) or (${item_status} != 'Active' and ${products.is_published} is false))
      and ((${item_substitute_group} = ${products.substitute_group}) or (${item_substitute_group} is null and ${products.substitute_group} is null))
      and ((${item_weight} = ${products.weight}) or (${item_weight} is null and ${products.weight} is null))
      and ${noos_item} = ${products.is_noos_group}
      and ${noos_leading_product} = ${products.is_leading_product}

      ;;
    description: "Boolean that indicates if what we have in the ERP matches what we have in CT"
    label: "Is ERP/CT Sync"
    group_label: "Special Uses Cases Data"
  }



#############################################
############## Measures Dimensions ##########
#############################################

  measure: cnt_leading_skus  {
    label: "# Leading SKUs"
    type: count_distinct
    sql: ${sku} ;;
    filters: [is_leading_sku: "yes"]
    description: "Total count of leading SKUs"
    group_label: "Measures"

    value_format_name: decimal_1
  }

  measure: cnt_skus {
    label: "# unique SKUs"
    type: count_distinct
    sql: ${sku} ;;
    description: "Total count of unique SKUs"
    group_label: "Measures"

    value_format_name: decimal_1
  }

  measure: count {
    type: count
    hidden: yes
    drill_fields: [item_name]
  }
}
