view: event_checkout_viewed {
  sql_table_name: `flink-data-prod.curated.event_checkout_viewed`
    ;;

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~     Dimensions    ~~~~~~~~~~~~~~~ #
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

  # ======= IDs ======= #

  dimension: anonymous_id {
    type: string
    sql: ${TABLE}.anonymous_id ;;
  }

  dimension: event_uuid {
    type: string
    primary_key: yes
    sql: ${TABLE}.event_uuid ;;
  }

  dimension: cart_id {
    type: string
    description: "A unique identifier for the cart. Not available on Android"
    sql: ${TABLE}.cart_id ;;
  }

  dimension: user_id {
    type: string
    sql: ${TABLE}.user_id ;;
  }

  dimension: device_id {
    required_access_grants: [can_access_pii_customers]
    type: string
    hidden: yes
    sql: ${TABLE}.device_id ;;
  }

  dimension: shipping_method_id {
    type: string
    description: "Unique ID of the shipping method. Generated by Commerce Tools."
    sql: ${TABLE}.shipping_method_id ;;
  }

# ======= Generic Dimensions ======= #

  dimension: has_selected_address {
    group_label: "Generic Dimensions"
    type: yesno
    sql: ${TABLE}.has_selected_address ;;
  }

  dimension: is_user_logged_in {
    group_label: "Generic Dimensions"
    type: yesno
    sql: ${TABLE}.is_user_logged_in ;;
  }

  dimension: event_name {
    group_label: "Generic Dimensions"
    type: string
    sql: ${TABLE}.event_name ;;
  }


# ======= Location Dimension ======= #

  dimension: country_iso {
    group_label: "Location Dimensions"
    type: string
    description: "Country of User"
    sql: ${TABLE}.country_iso ;;
  }

  dimension: hub_code {
    group_label: "Location Dimensions"
    type: string
    description: "Hub assigned to User"
    sql: ${TABLE}.hub_code ;;
  }

  dimension: locale {
    group_label: "Location Dimensions"
    type: string
    hidden: yes
    sql: ${TABLE}.locale ;;
  }

  dimension: timezone {
    group_label: "Location Dimensions"
    type: string
    description: "Timezone of User"
    sql: ${TABLE}.timezone ;;
  }


# ======= Device Dimensions ======= #

  dimension: app_version {
    group_label: "Device Dimensions"
    type: string
    description: "App_version of the device"
    sql: ${TABLE}.app_version ;;
  }

  dimension: device_model {
    group_label: "Device Dimensions"
    type: string
    description: "Device Model"
    sql: ${TABLE}.device_model ;;
  }

  dimension: device_type {
    group_label: "Device Dimensions"
    type: string
    description: "Device Type"
    sql: ${TABLE}.device_type ;;
  }

  dimension: os_version {
    group_label: "Device Dimensions"
    type: string
    description: "OS Version of the device used"
    sql: ${TABLE}.os_version ;;
  }

  dimension: platform {
    group_label: "Device Dimensions"
    type: string
    description: "Platform is either iOS, Android or Web"
    sql: ${TABLE}.platform ;;
  }

# ======= Dynamic Delivery Fee Dimensions ======= #

  dimension: amt_delivery_fee_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Delivery fee applicable for the users order at the time the event was triggered"
    sql: ${TABLE}.delivery_fee ;;
  }

  dimension: amt_storage_fee_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Storage fee applicable for the user at the time the event was triggered."
    sql: ${TABLE}.storage_fee ;;
  }

  dimension: amt_late_night_fee_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Late night fee applicable for the user at the time the event was triggered."
    sql: ${TABLE}.late_night_fee ;;
  }

  dimension: amt_deposit_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Total of deposit that is part of user's order."
    sql: ${TABLE}.deposit ;;
  }

  dimension: amt_discount_value_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Value of the discount applied."
    sql: ${TABLE}.discount_value ;;
  }

  dimension: amt_order_subtotal_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Total value of the items in the order, excluding fees, deposit, tax, cart discounts. Including item discounts."
    sql: ${TABLE}.order_subtotal ;;
  }

  dimension: amt_order_total_eur {
    group_label: "DDF Dimensions"
    type: number
    description: "Total value of the order including all fees, tax and discounts."
    sql: ${TABLE}.order_total ;;
  }

  dimension: products {
    group_label: "DDF Dimensions"
    type: string
    description: "Products purchased by user."
    sql: ${TABLE}.products ;;
  }

  dimension: delivery_pdt {
    type: number
    description: "Delivery PDT a user saw on Checkout Screen. Available only on mobile platforms"
    sql:  ${TABLE}.delivery_pdt ;;
  }



# ======= Dates / Timestamps =======

  dimension_group: event {
    type: time
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.event_date ;;
  }


# ======= Hidden =======

  dimension_group: event_timestamp {
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    hidden:  yes
    sql: ${TABLE}.event_timestamp ;;
  }


  dimension_group: received {
    type: time
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    hidden: yes
    sql: ${TABLE}.received_at ;;
  }


# ======= Measures ======= #


  measure: all_users {
    group_label: "Measure Dimensions"
    description: "Number of all users regardless of their login status."
    type: count_distinct
    sql: ${TABLE}.anonymous_id ;;
  }

}
