view: event_order_tracking_viewed {
  sql_table_name: `flink-data-prod.curated.event_order_tracking_viewed`
    ;;

  dimension: anonymous_id {
    type: string
    description: "Unique ID for each user set by Segement."
    sql: ${TABLE}.anonymous_id ;;
  }

  dimension: app_version {
    type: string
    description: "Version of the app released, available for apps only."
    sql: ${TABLE}.app_version ;;
  }

  dimension: country_iso {
    type: string
    description: "Country ISO based on 'hub_code'."
    sql: ${TABLE}.country_iso ;;
  }

  dimension: delivery_eta {
    type: number
    description: "Estimated Time Arrival upon delivery to selected address, in minutes (after order is placed)"
    sql: ${TABLE}.delivery_eta ;;
  }

  dimension: delivery_lat {
    type: number
    description: "Latitude of the address selected by the customer."
    sql: ${TABLE}.delivery_lat ;;
  }

  dimension: delivery_lng {
    type: number
    description: "Longitude of the address selected by the customer."
    sql: ${TABLE}.delivery_lng ;;
  }

  dimension: delivery_pdt {
    type: number
    description: "PDT (promised delivery time) - time estimation (in mintues) when users can expect their order to be delivered."
    sql: ${TABLE}.delivery_pdt ;;
  }

  dimension: device_id {
    type: string
    description: "Unique ID for each device."
    sql: ${TABLE}.device_id ;;
  }

  dimension: device_model {
    type: string
    description: "Model of the device, available for apps only."
    sql: ${TABLE}.device_model ;;
  }

  dimension: device_type {
    type: string
    description: "Type of the device used, e.i. ios, android, windows, etc."
    sql: ${TABLE}.device_type ;;
  }

  dimension_group: event {
    type: time
    description: "Date when an event was triggered."
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.event_date ;;
  }

  dimension: event_name {
    type: string
    description: "Name of an event triggered."
    sql: ${TABLE}.event_name ;;
  }

  dimension_group: event_timestamp {
    type: time
    description: "Timestamp when an event was triggered within the app / web."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.event_timestamp ;;
  }

  dimension: event_uuid {
    type: string
    description: "Unique ID for each event defined by Segment."
    sql: ${TABLE}.event_uuid ;;
  }

  dimension: has_selected_address {
    type: yesno
    description: "TRUE if upon launch the user had a previously confirmed address."
    sql: ${TABLE}.has_selected_address ;;
  }

  dimension: hub_code {
    type: string
    description: "Code of a hub identical to back-end source tables."
    sql: ${TABLE}.hub_code ;;
  }

  dimension: is_user_logged_in {
    type: yesno
    description: "TRUE if a user was logged during browsing."
    sql: ${TABLE}.is_user_logged_in ;;
  }

  dimension: locale {
    type: string
    description: "Locale on the device."
    sql: ${TABLE}.locale ;;
  }

  dimension: order_id {
    type: string
    description: "Unique identifier generated by back-end when an order is placed."
    sql: ${TABLE}.order_id ;;
  }

  dimension: order_status {
    type: string
    description: "Status of the order. E.g. confirmed, packing, delivered"
    sql: ${TABLE}.order_status ;;
  }

  dimension: os_version {
    type: string
    description: "Version of the operating system, avaialble for apps only."
    sql: ${TABLE}.os_version ;;
  }

  dimension: page_path {
    type: string
    description: "Page path of users' page view. Page path does not contain domain information nor query parameters."
    sql: ${TABLE}.page_path ;;
  }

  dimension: platform {
    type: string
    description: "Platform which user used, can be 'web' or 'app'."
    sql: ${TABLE}.platform ;;
  }

  dimension_group: received {
    type: time
    description: "Timestamp when an event was received on the server, used for data laod."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.received_at ;;
  }

  dimension: screen_name {
    type: string
    description: "Name of the screen where the event occurs, in human readable form. This should be consistent for all events fired on the same screen."
    sql: ${TABLE}.screen_name ;;
  }

  dimension: timezone {
    type: string
    description: "Timezone of the device located."
    sql: ${TABLE}.timezone ;;
  }

  dimension: user_id {
    type: string
    description: "Unique ID for each user set upon account creation. This ID is passed under all behaviorual events when a user is logged in and is identical to the External ID under back-end models such as \"orders\"."
    sql: ${TABLE}.user_id ;;
  }

  measure: count {
    type: count
    drill_fields: [screen_name, event_name]
  }
}
