# Owner: Product Analytics, Bastian Gerstner

# Main Stakeholder:
# - Last Mile Tech Team

# Questions that can be answered
# - Questions around behavioural events originating from rider app

include: "/product_consumer/views/bigquery_curated/daily_rider_app_events.view.lkml"
include: "/**/global_filters_and_parameters.view.lkml"


explore: daily_rider_app_events {
  from:  daily_rider_app_events
  view_name: daily_rider_app_events
  hidden: no

  label: "Daily Rider App Events"
  description: "This explore provides an overview of all behavioural events generated by Flink Rider App"
  group_label: "Last Mile"

  # implement both date filters:
  # received_at is due cost reduction given a table is partitioned by this dimensions
  # event_date filter will fitler for the desired time frame when events triggered

  sql_always_where:{% condition global_filters_and_parameters.datasource_filter %} date(${event_timestamp_date}) {% endcondition %};;


  always_filter: {
    filters: [
      global_filters_and_parameters.datasource_filter: "last 7 days"
    ]
  }

  join: global_filters_and_parameters {
    sql_on: ${global_filters_and_parameters.generic_join_dim} = TRUE ;;
    type: left_outer
    relationship: many_to_one
  }
}
