# Owner: Product Analytics, Flavia Alvarez
# Created: 2022-11-24

view: hub_one_picking_times {
  sql_table_name: `flink-data-prod.reporting.hub_one_picking_times`
    ;;

  view_label: "Picking Times"

  # This is a table from the reporting layer that calculates the picking times

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Sets          ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

set: to_include_dimensions {
fields: [
  order_picked_time,
  order_picking_finished_time,
  order_packed_time,

  picker_quinyx_badge_number
  ]
}

set: to_include_measures {
  fields: [
    sum_of_picking_time_seconds,
    sum_of_picking_time_minutes,
    sum_of_picking_time_hours,
    sum_of_container_assignment_time_seconds,
    sum_of_container_assignment_time_minutes,
    sum_of_container_assignment_time_hours,
    sum_of_picking_items_time_seconds,
    sum_of_picking_items_time_minutes,
    sum_of_picking_items_time_hours,

    avg_of_picking_time_seconds,
    avg_of_picking_time_minutes,
    avg_of_container_assignment_time_seconds,
    avg_of_container_assignment_time_minutes,
    avg_of_picking_items_time_seconds,
    avg_of_picking_items_time_minutes
  ]
}

set: to_include_set {
  fields: [to_include_dimensions*, to_include_measures*]
}

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Parameters     ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Dimensions     ~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # =========  IDs   =========

  dimension: table_uuid {
    type: string
    description: "Concatenation of event_date and order_id."
    sql: ${TABLE}.table_uuid ;;
  }

  dimension: order_id {
    type: string
    description: "Unique identifier generated by back-end when an order is placed."
    sql: ${TABLE}.order_id ;;
  }

  # =========  Location Dimensions   =========

  dimension: country_iso {
    type: string
    group_label: "Location Dimensions"
    label: "Country ISO"
    description: "Country ISO based on 'hub_code'."
    sql: ${TABLE}.country_iso ;;
  }

  dimension: hub_code {
    type: string
    group_label: "Location Dimensions"
    label: "Hub Code"
    description: "Code of a hub identical to back-end source tables."
    sql: ${TABLE}.hub_code ;;
  }

  # =========  Employee Attributes   =========

  dimension: picker_quinyx_badge_number {
    group_label: "Event Properties"
    type: string
    description: "Quinyx Badge number of the employee who started the picking process first."
    sql: ${TABLE}.picker_quinyx_badge_number ;;
  }

  # =========  Dates and Timestamps   =========

  dimension_group: event {
    type: time
    description: "Date when an event was triggered."
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.event_date ;;
  }

  dimension_group: order_picked {
    group_label: "Picking Times"
    label: "Order Picked Time"
    type: time
    description: "Timestamp for when the order is selected by the picker (state= picked)."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.order_picked_at ;;
  }

  dimension_group: order_picking_finished {
    group_label: "Picking Times"
    label: "Order Picking Finished Time"
    type: time
    description: "Timestamp for when the picker finished picking the items (state= picking_finished)."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.order_picking_finished_at ;;
  }

  dimension_group: order_packed {
    group_label: "Picking Times"
    label: "Order Packed Time"
    type: time
    description: "Timestamp for when the order is ready for the rider (state= packed)."
    timeframes: [
      raw,
      time,
      date,
      week,
      month,
      quarter,
      year
    ]
    sql: ${TABLE}.order_packed_at ;;
  }

  dimension: time_picking_items_seconds {
    type: number
    description: "Time spent picking items in seconds (difference between order_picked and order_picking_finished)."
    sql: ${TABLE}.time_picking_items_seconds ;;
  }

  dimension: time_picking_items_minutes {
    type: number
    description: "Time spent picking items in minutes (difference between order_picked and order_picking_finished)."
    sql: ${TABLE}.time_picking_items_minutes ;;
  }

  dimension: time_assigning_containers_seconds {
    type: number
    description: "Time spent assigning containers and shelfs in seconds (difference between order_picking_finished_at and order_packed_at)."
    sql: ${TABLE}.time_assigning_containers_seconds ;;
  }

  dimension: time_assigning_containers_minutes {
    type: number
    description: "Time spent assigning containers and shelfs in minutes (difference between order_picking_finished_at and order_packed_at)."
    sql: ${TABLE}.time_assigning_containers_minutes ;;
  }

  dimension: time_picking_process_seconds {
    type: number
    description: "Time spent picking an order from order picked to order ready for rider in seconds (difference between order_picked_at and order_packed_at)."
    sql: ${TABLE}.time_picking_process_seconds ;;
  }

  dimension: time_picking_process_minutes {
    type: number
    description: "Time spent picking an order from order picked to order ready for rider in minutes (difference between order_picked_at and order_packed_at)."
    sql: ${TABLE}.time_picking_process_minutes ;;
  }

  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~     Measures     ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # Note that for this measures to be accurate we need to use sum_distinct with sql_distinct_key = order_id
  # This is because this view is being joined to daily_events and if we use a normal sum it will be suming
  # duplicate values

  # =========  Total Times   =========

  measure: sum_of_picking_time_seconds {
    group_label: "Total Times"
    label: "Picking Time seconds"
    description: "Sum of time spent picking an order from order picked to order ready for rider in seconds."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_seconds} ;;
  }

  measure: sum_of_picking_time_minutes {
    group_label: "Total Times"
    label: "Picking Time minutes"
    description: "Sum of time spent picking an order from order picked to order ready for rider in minutes."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes} ;;
  }

  measure: sum_of_picking_time_hours {
    group_label: "Total Times"
    label: "Picking Time hours"
    description: "Sum of time spent picking an order from order picked to order ready for rider in hours."
    type: sum_distinct
    value_format: "0.#"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes}/60 ;;
  }

  measure: sum_of_container_assignment_time_seconds {
    group_label: "Total Times"
    label: "Container Assignment Time seconds"
    description: "Sum of time spent on assign containers and shelfs in seconds."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_assigning_containers_seconds} ;;
  }

  measure: sum_of_container_assignment_time_minutes {
    group_label: "Total Times"
    label: "Container Assignment Time minutes"
    description: "Sum of time spent on assign containers and shelfs in minutes."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_assigning_containers_minutes} ;;
  }

  measure: sum_of_container_assignment_time_hours {
    group_label: "Total Times"
    label: "Container Assignment Time hours"
    description: "Sum of time spent on assign containers and shelfs in hours."
    type: sum_distinct
    value_format: "0.#"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_assigning_containers_minutes}/60 ;;
  }

  measure: sum_of_picking_items_time_seconds {
    group_label: "Total Times"
    label: "Picking Items Time seconds"
    description: "Sum of time spent picking items from order picked to container assignment in seconds."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_seconds} ;;
  }

  measure: sum_of_picking_items_time_minutes {
    group_label: "Total Times"
    label: "Picking Items Time minutes"
    description: "Sum of time spent picking items from order picked to container assignment in minutes."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes} ;;
  }

  measure: sum_of_picking_items_time_hours {
    group_label: "Total Times"
    label: "Picking Items Time hours"
    description: "Sum of time spent picking items from order picked to container assignment in hours."
    type: sum_distinct
    value_format: "0"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes}/60 ;;
  }

  # =========  Average Times   =========

  measure: avg_of_picking_time_seconds {
    group_label: "Avg Times"
    label: "Avg Picking Time seconds"
    description: "Avg of time spent picking an order from order picked to order ready for rider in seconds."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_seconds} ;;
  }

  measure: avg_of_picking_time_minutes {
    group_label: "Avg Times"
    label: "Avg Picking Time minutes"
    description: "Avg of time spent picking an order from order picked to order ready for rider in minutes."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes} ;;
  }

  measure: avg_of_container_assignment_time_seconds {
    group_label: "Avg Times"
    label: "Avg Container Assignment Time seconds"
    description: "Avg of time spent on assign containers and shelfs in seconds."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_assigning_containers_seconds} ;;
  }

  measure: avg_of_container_assignment_time_minutes {
    group_label: "Avg Times"
    label: "Avg Container Assignment Time minutes"
    description: "Avg of time spent on assign containers and shelfs in minutes."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_assigning_containers_minutes} ;;
  }

  measure: avg_of_picking_items_time_seconds {
    group_label: "Avg Times"
    label: "Avg Picking Items Time seconds"
    description: "Avg of time spent picking items from order picked to container assignment in seconds."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_seconds} ;;
  }

  measure: avg_of_picking_items_time_minutes {
    group_label: "Avg Times"
    label: "Avg Picking Items Time minutes"
    description: "Avg of time spent picking items from order picked to container assignment in minutes."
    type: average_distinct
    value_format: "0.00"
    sql_distinct_key: ${order_id} ;;
    sql: ${time_picking_process_minutes} ;;
  }
}
