# Owner: Pete Kell
# Created: 2022-03-21

view: picker_order_progress_sku_aggregates {
  sql_table_name: `flink-data-prod.reporting.picker_order_progress_sku_aggregates`
    ;;


  # This is a reporting layer aggregated table based on the event stream data generated by the picker app.
  # It should be used only to understand how pickers progress through the picking process.

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~     Dimensions     ~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  # ~~ IDs & Date Filters ~~

  dimension: country_iso {
    type: string
    sql: ${TABLE}.country_iso ;;
  }

  dimension_group: date {
    type: time
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.date ;;
  }

  dimension: hub_code {
    type: string
    sql: ${TABLE}.hub_code ;;
  }

  dimension: order_id {
    type: string
    sql: ${TABLE}.order_id ;;
  }


  # ~~ Product Filters ~~

  dimension: category {
    type: string
    sql: ${TABLE}.category ;;
  }

  dimension: is_ean_available {
    type: yesno
    sql: ${TABLE}.is_ean_available ;;
  }

  dimension: product_name {
    type: string
    sql: ${TABLE}.product_name ;;
  }

  dimension: sku {
    type: string
    sql: ${TABLE}.sku ;;
  }

  # ~~ Aggregated Columns ~~

  dimension: number_of_code_damanged {
    type: number
    sql: ${TABLE}.number_of_code_damanged ;;
  }

  dimension: number_of_code_wrong {
    type: number
    sql: ${TABLE}.number_of_code_wrong ;;
  }

  dimension: number_of_item_picked {
    type: number
    sql: ${TABLE}.number_of_item_picked ;;
  }

  dimension: number_of_item_unavailable {
    type: number
    sql: ${TABLE}.number_of_item_unavailable ;;
  }

  dimension: order_product_uuid {
    type: string
    hidden: yes
    sql: ${TABLE}.order_product_uuid ;;
  }

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~     Measures.      ~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  measure: count {
    type: count
    drill_fields: [product_name]
  }

  measure: sum_of_code_damanged {
    type: sum
    sql: ${TABLE}.number_of_code_damanged ;;
  }

  measure: sum_of_code_wrong {
    type: sum
    sql: ${TABLE}.number_of_code_wrong ;;
  }

  measure: sum_of_item_picked {
    type: sum
    sql: ${TABLE}.number_of_item_picked ;;
  }

  measure: sum_of_item_unavailable {
    type: sum
    sql: ${TABLE}.number_of_item_unavailable ;;
  }

  measure: number_of_orders {
    type: count_distinct
    sql: ${TABLE}.order_id ;;
  }
}
