# Owner: Pete Kell
# Created: 2022-03-21

view: picker_order_progress_sku_aggregates {
  sql_table_name: `flink-data-prod.reporting.picker_order_progress_sku_aggregates`
    ;;


  # This is a reporting layer aggregated table based on the event stream data generated by the picker app.
  # It should be used only to understand how pickers progress through the picking process.

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~     Dimensions     ~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ### Dates ###

  dimension_group: date {
    group_label: "Date Dimensions"
    label: ""
    type: time
    timeframes: [
      raw,
      date,
      week,
      month,
      quarter,
      year
    ]
    convert_tz: no
    datatype: date
    sql: ${TABLE}.date ;;
  }

  ### Location Atributes ###

  dimension: country_iso {
    group_label: "Location Dimensions"
    label: "Country ISO"
    type: string
    sql: ${TABLE}.country_iso ;;
  }

  dimension: hub_code {
    group_label: "Location Dimensions"
    type: string
    sql: ${TABLE}.hub_code ;;
  }

  ### Order IDs ###

  dimension: order_id {
    group_label: "Order ID"
    type: string
    sql: ${TABLE}.order_id ;;
  }

  dimension: order_product_uuid {
    hidden: yes
    type: string
    sql: ${TABLE}.order_product_uuid ;;
  }

  ### Product Filters ###

  dimension: category {
    group_label: "Product Attributes"
    type: string
    sql: ${TABLE}.category ;;
  }

  dimension: is_ean_available {
    group_label: "Product Attributes"
    type: yesno
    sql: ${TABLE}.is_ean_available ;;
  }

  dimension: product_name {
    group_label: "Product Attributes"
    type: string
    sql: ${TABLE}.product_name ;;
  }

  dimension: sku {
    group_label: "Product Attributes"
    type: string
    sql: ${TABLE}.sku ;;
  }

  ### Hidden Columns ###

  dimension: number_of_code_damanged {
    hidden: yes
    type: number
    sql: ${TABLE}.number_of_code_damanged ;;
  }

  dimension: number_of_code_wrong {
    hidden: yes
    type: number
    sql: ${TABLE}.number_of_code_wrong ;;
  }

  dimension: number_of_item_picked {
    hidden: yes
    type: number
    sql: ${TABLE}.number_of_item_picked ;;
  }

  dimension: number_of_item_unavailable {
    hidden: yes
    type: number
    sql: ${TABLE}.number_of_item_unavailable ;;
  }

  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~     Measures.      ~~~~~~~~~~~~~~~~~~~~~~~~~
  #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  ### Sum and count Metrics ###

  measure: count {
    type: count
    drill_fields: [product_name]
  }

  measure: total_code_damanged {
    group_label: "Total Metrics"
    type: sum
    sql: ${TABLE}.number_of_code_damanged ;;
  }

  measure: total_code_wrong {
    group_label: "Total Metrics"
    type: sum
    sql: ${TABLE}.number_of_code_wrong ;;
  }

  measure: total_item_unavailable {
    group_label: "Total Metrics"
    type: sum
    sql: ${TABLE}.number_of_item_unavailable ;;
  }

  measure: total_item_picked {
    group_label: "Total Metrics"
    type: sum
    sql: ${TABLE}.number_of_item_picked ;;
  }

  measure: total_items {
    group_label: "Total Metrics"
    type: sum
    description: "# items picked + items swiped (code_wrong + code_damaged) + items unavailable"
    sql: (${TABLE}.number_of_code_damanged + ${TABLE}.number_of_code_wrong + ${TABLE}.number_of_item_unavailable +  ${TABLE}.number_of_item_picked) ;;
  }

  measure: number_of_orders {
    group_label: "Total Metrics"
    type: count_distinct
    sql: ${TABLE}.order_id ;;
  }

  ### Rate metrics ###

  measure: swiped_items_per_total_items {
    group_label: "Rate Metrics"
    label: "% Swiped EAN Items"
    type: number
    description: "# items swiped (code_wrong + code_damaged) / # total items"
    value_format_name: percent_1
    sql: ((${total_code_wrong}+${total_code_damanged}) / nullif((${total_items}),0) ;;
  }

  measure: unavailable_items_per_total_items {
    group_label: "Rate Metrics"
    label: "% Partial Fulfilment"
    type: number
    description: "# items unavailable / # total items"
    value_format_name: percent_1
    sql: ((${total_item_unavailable}) / nullif((${total_items}),0) ;;
  }
}
