# Owner: Pete Kell

# Main Stakeholder:
# - Hub Tech
# - Hub Operations

# Questions that can be answered
# - How pickers use the functionality of the picker app

include: "/views/bigquery_tables/curated_layer/daily_picker_events.view"
include: "/views/bigquery_tables/curated_layer/products.view"
include: "/**/global_filters_and_parameters.view.lkml"

explore: daily_picker_events {
  from:  daily_picker_events
  view_name: daily_picker_events

  label: "Daily Picker Events"
  description: "This explore provides an overview of the front-end events generated by the picker app."
  group_label: "Consumer Product"

  access_filter: {
    field: daily_picker_events.country_iso
    user_attribute: country_iso
  }

  always_filter: {
    filters: [
      global_filters_and_parameters.datasource_filter: "last 7 days"
    ]
  }

  join: global_filters_and_parameters {
    sql_on: ${global_filters_and_parameters.generic_join_dim} = TRUE ;;
    type: left_outer
    relationship: many_to_one
  }

  join: products {
    sql_on: ${daily_picker_events.sku} = ${products.product_sku} ;;
    type: left_outer
    relationship: many_to_one
  }
}
