# Owner: Brandon Beckett
# Created: 2022-10-31

# This view contains CommerceTools shipping method data and the respective delivery fee tier and price setups.
# This data can be joined on shipping_method_id and country_iso to either the orders or hubs views.

view: shipping_methods_ct {
  sql_table_name: `flink-data-prod.curated.shipping_methods_ct`;;
  view_label: "Shipping Methods"

# ====================      Sets      ====================

  set: orders_df_fields {
    fields: [
      shipping_method_id,
      amt_delivery_fee_gross,
      amt_order_value_threshold_net,
      delivery_fee_tier,
      delivery_fee_tier_type
    ]
  }

# ====================      Dates & Timestamps      ====================

  dimension_group: created_at_timestamp {

    label: "Shipping Method Created at"
    description: "Date and time (UTC) the Shipping Method was initially created within the project settings in CommerceTools."
    group_label: "Delivery Fees & Thresholds"

    type: time
    timeframes: [
      time,
      date,
      week,
      month,
      year
    ]
    sql: ${TABLE}.created_at_timestamp ;;
  }

  dimension_group: last_modified_at_timestamp {

    label: "Shipping Method Last Modified at"
    description: "Date and time (UTC) the Shipping Method was last updated within the project settings in CommerceTools."
    group_label: "Delivery Fees & Thresholds"

    type: time
    timeframes: [
      time,
      date,
      week,
      month,
      year
    ]
    sql: ${TABLE}.last_modified_at_timestamp ;;
  }

  dimension: run_started_at_timestamp {

    label: "Run Started at"
    description: "Date and time this model last successfully ran."
    group_label: "Dates & Timestamps"

    type: string
    sql: ${TABLE}.run_started_at_timestamp ;;
    hidden: yes
  }

# ====================      IDs      ====================

  dimension: table_uuid {

    label: "Table UUID"
    description: "Generic identifier of a table in BigQuery that represent 1 unique row of this table."
    group_label: "IDs"

    type: string
    sql: ${TABLE}.table_uuid ;;

    primary_key: yes
    hidden: yes
  }

  dimension: shipping_method_id {

    label: "Shipping Method ID"
    description: "Unique ID of the shipping method. Generated by the backend."
    group_label: "Delivery Fees & Thresholds"

    link: {
      label: "View this Shipping Method in CommerceTools"
      url: "https://mc.europe-west1.gcp.commercetools.com/flink-production/settings/project/shipping-methods/{{ value }}"
    }

    type: string
    sql: ${TABLE}.shipping_method_id ;;
  }

  dimension: shipping_method_key {

    label: "Shipping Method Key"
    description: "User-defined unique identifier of the ShippingMethod."
    group_label: "Delivery Fees & Thresholds"

    type: string
    sql: ${TABLE}.shipping_method_key ;;
  }

  dimension: zone_id {

    label: "Zone ID"
    description: "ID representing the Country ISO that the shipping method applies to, generated by the backend."
    group_label: "Delivery Fees & Thresholds"

    type: string
    sql: ${TABLE}.zone_id ;;
    hidden: yes
  }

# ====================      Delivery Fees & Thresholds      ====================

  dimension: country_iso {

    label: "Country Iso"
    description: "Country ISO based on CommerceTools Zone ID."
    group_label: "Delivery Fees & Thresholds"

    type: string
    sql: ${TABLE}.country_iso ;;
  }

  dimension: amt_delivery_fee_gross {

    label: "Delivery Fee Gross"
    description: "Cost of the delivery fee for user's order dependent on the given Order Value Threshold Net"
    group_label: "Delivery Fees & Thresholds"

    type: number
    value_format_name: eur
    sql: ${TABLE}.amt_delivery_fee_gross ;;
  }

  dimension: amt_order_value_threshold_net {

    label: "Order Value Threshold Net"
    description: "Minimum basket value required to receive the corresponding delivery fee."
    group_label: "Delivery Fees & Thresholds"

    type: number
    value_format_name: eur_0
    sql: ${TABLE}.amt_order_value_threshold_net ;;
  }

  dimension: delivery_fee_tier {

    label: "Delivery Fee Tier"
    description: "Delivery fees are applied by basket value ranges and defined via tiers. The lowest tier represents the lowest basket value required and vice versa."
    group_label: "Delivery Fees & Thresholds"

    type: number
    sql: ${TABLE}.delivery_fee_tier ;;
  }

  dimension: delivery_fee_tier_type {

    label: "Delivery Fee Tier Type"
    description: "Description of the delivery fee tier."
    group_label: "Delivery Fees & Thresholds"

    type: string
    sql: ${TABLE}.delivery_fee_tier_type ;;
  }

}
